services:
  valheim:
    env_file:
      - valheim.env
    restart: unless-stopped
    image: mbround18/valheim:latest
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
  factorio:
    env_file:
      - factorio.env
    restart: unless-stopped
    image: factoriotools/factorio
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ./factorio:/factorio
  satisfactory:
    env_file:
      - satisfactory.env
    restart: unless-stopped
    image: wolveix/satisfactory-server:latest
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - ./satisfactory:/config
  minecraft:
    build: ./docker/minecraft
    env_file:
      - minecraft.env
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - ./minecraft:/data
