version: "3.9"  # optional since v1.27.0
services:
  valheim:
    container_name:    valheim
    build:             ./steam
    restart:           unless-stopped
    tty: true
    environment:
      STEAMAPPID: 896660
      STEAMAPP: "Valheim dedicated server"
      SERVER_PW: "jakethesnake" 
      SERVER_NAME: "Two Wars" 
      SERVER_WORLD: "Bird Law"
      SERVER_PUBLIC: "1"
      STEAMCMD_UPDATE_ARGS: "" 
      ADDITIONAL_ARGS: ""
    ports:
      - target: 2456
        published: 2456
        protocol: udp
        mode: host
      - target: 2457
        published: 2457
        protocol: udp
        mode: host
      - target: 2458
        published: 2458
        protocol: udp
        mode: host
    volumes:
      - ./steam/etc/:/home/steam/etc
      - valheim_data:/home/steam/.config/unity3d/IronGate/Valheim
    command: ['bash', './etc/entry.sh']
    networks:
      - valheim_network

volumes:
  valheim_data:

networks:
  valheim_network:
