services:
  # valheim:
  #   env_file:
  #     - valheim.env
  #   image: mbround18/valheim:latest
  #   ports:
  #     - "2456-2457:2456-2457/udp"
  #   volumes:
  #     - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
  #     - ./valheim/server:/home/steam/valheim
  factorio:
    env_file:
      - factorio.env
    image: factoriotools/factorio
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - ./factorio:/factorio