services:
  valheim:
    env_file:
      - valheim.env
    image: mbround18/valheim:latest
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
  factorio:
    env_file:
      - factorio.env
    image: factoriotools/factorio
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ./factorio:/factorio
  satisfactory:
    env_file:
      - satisfactory.env
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - './satisfactory:/config'

    restart: unless-stopped