FROM cm2network/steamcmd:root

LABEL maintainer="walentinlamonos@gmail.com"
COPY ./etc /home/steam/etc
ENV STEAMAPPDIR "/home/steam/valheim"
ENV DLURL https://raw.githubusercontent.com/CM2Walki/Mordhau

RUN mkdir ${STEAMAPPDIR}

RUN chmod +x "${HOMEDIR}/etc/entry.sh"
RUN chown -R "${USER}:${USER}" "${HOMEDIR}/etc/entry.sh" "${STEAMAPPDIR}"
RUN set -x \
	# Install, update & upgrade packages
	&& apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		libfontconfig1=2.13.1-4.2 \
		libpangocairo-1.0-0=1.46.2-3 \
		libnss3=2:3.61-1+deb11u2 \
		gconf-gsettings-backend=3.2.6-7 \
		libxi6=2:1.7.10-1 \
		libxcursor1=1:1.2.0-2 \
		libxss1=1:1.2.3-1 \
		libxcomposite1=1:0.4.5-1 \
		libasound2=1.2.4-1.1 \
		libxdamage1=1:1.1.5-2 \
		libxtst6=2:1.2.3-1 \
		libatk1.0-0=2.36.0-2 \
		libxrandr2=2:1.5.1-1 \
		libcurl3-gnutls=7.74.0-1.3+deb11u1 \
		libcurl4=7.74.0-1.3+deb11u1 \
		wget=1.21-1+deb11u1 \
		ca-certificates=20210119 \
		iputils-ping=3:20210202-1 \
	# Clean up
	&& rm -rf /var/lib/apt/lists/*


# Switch to user
USER ${USER}

WORKDIR ${HOMEDIR}